[package]
name = "rustvent"
version = "0.1.0"
edition = "2021"

[lib]
name = "adventlib"
path = "src/lib.rs"

[[bin]]
name = "rustvent"
path = "src/main.rs"

[dependencies]
clap = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
